[build]
  publish = "."

[[redirects]]
  from = "/auth/patreon"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/stall/*"
  to = "/stall/index.html"
  status = 200

[[redirects]]
  from = "/directory"
  to = "/directory.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/signup.html"
  status = 200

[[redirects]]
  from = "/whats-on"
  to = "/whats-on.html"
  status = 200

[[redirects]]
  from = "/kid-finder"
  to = "/kid-finder.html"
  status = 200
